VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IQueryBuilder"

'@Module: [NomDuModule]
'@Description: 
'@Version: 1.0
'@Date: 13/04/2025
'@Author: APEX Framework Team

Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' ==========================================================================
' Module    : IQueryBuilder
' État      : À DÉVELOPPER (Stub)
' Description : Interface pour la construction de requêtes SQL.
' Date de création : 11/04/2025
' ==========================================================================

' -- Interface stub --
